package com.biblelib.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Palette derived from the BibleLib mark: a bold vivid orange "B" with warm-grey layered shadows.
object LightColors {
    val primary = Color(0xFFE1550F)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFFFDBC7)
    val onPrimaryContainer = Color(0xFF3A1300)
    val secondary = Color(0xFF75655C)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFFFDBC7)
    val onSecondaryContainer = Color(0xFF2B1D16)
    val tertiary = Color(0xFF8C4A1E)
    val onTertiary = Color(0xFFFFFFFF)
    val tertiaryContainer = Color(0xFFFFDBC3)
    val onTertiaryContainer = Color(0xFF301300)
    val error = Color(0xFFBA1A1A)
    val errorContainer = Color(0xFFFFDAD6)
    val onError = Color(0xFFFFFFFF)
    val onErrorContainer = Color(0xFF410002)
    val background = Color(0xFFFFFBFF)
    val onBackground = Color(0xFF211A15)
    val surface = Color(0xFFFFFBFF)
    val onSurface = Color(0xFF211A15)
    val surfaceVariant = Color(0xFFF4DED2)
    val onSurfaceVariant = Color(0xFF53433B)
    val outline = Color(0xFF85736A)
    val inverseOnSurface = Color(0xFFFBEEE7)
    val inverseSurface = Color(0xFF362F2A)
    val inversePrimary = Color(0xFFFFB690)
    val shadow = Color(0xFF000000)
    val surfaceTint = Color(0xFFE1550F)
    val outlineVariant = Color(0xFFD8C2B7)
    val scrim = Color(0xFF000000)
}

object DarkColors {
    val primary = Color(0xFFFFB690)
    val onPrimary = Color(0xFF5A2000)
    val primaryContainer = Color(0xFF7F3300)
    val onPrimaryContainer = Color(0xFFFFDBC7)
    val secondary = Color(0xFFE3C3B4)
    val onSecondary = Color(0xFF422C22)
    val secondaryContainer = Color(0xFF5A4136)
    val onSecondaryContainer = Color(0xFFFFDBC7)
    val tertiary = Color(0xFFFFB68F)
    val onTertiary = Color(0xFF502200)
    val tertiaryContainer = Color(0xFF703300)
    val onTertiaryContainer = Color(0xFFFFDBC3)
    val error = Color(0xFFFFB4AB)
    val errorContainer = Color(0xFF93000A)
    val onError = Color(0xFF690005)
    val onErrorContainer = Color(0xFFFFDAD6)
    val background = Color(0xFF181210)
    val onBackground = Color(0xFFECE0DA)
    val surface = Color(0xFF181210)
    val onSurface = Color(0xFFECE0DA)
    val surfaceVariant = Color(0xFF53433B)
    val onSurfaceVariant = Color(0xFFD8C2B7)
    val outline = Color(0xFFA08D83)
    val inverseOnSurface = Color(0xFF181210)
    val inverseSurface = Color(0xFFECE0DA)
    val inversePrimary = Color(0xFFE1550F)
    val shadow = Color(0xFF000000)
    val surfaceTint = Color(0xFFFFB690)
    val outlineVariant = Color(0xFF53433B)
    val scrim = Color(0xFF000000)
}
